name: nmr3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - aom=3.6.1
  - appdirs=1.4.4
  - asttokens=3.0.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.6.15
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - eval_type_backport=0.2.2
  - exceptiongroup=1.2.2
  - expat=2.6.4
  - ffmpeg=4.4.2
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.4
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - greenlet=3.1.1
  - h5py=3.13.0
  - hdf5=1.14.3
  - hydra-core=1.3.2
  - icu=73.2
  - idna=3.7
  - imageio=2.36.1
  - intel-openmp=2022.0.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=2.1.3
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - numpy=2.2.2
  - omegaconf=2.3.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.9
  - openssl=3.5.0
  - orc=2.0.3
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.44.2
  - platformdirs=4.3.6
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.50
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py3dmol=2.4.2
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pycairo=1.27.0
  - pydantic=2.10.5
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - rdkit=2024.03.6
  - re2=2024.07.02
  - readline=8.2
  - reportlab=4.2.5
  - requests=2.32.3
  - rlpycairo=0.2.0
  - s2n=1.5.11
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sentry-sdk=2.20.0
  - setproctitle=1.3.4
  - setuptools=75.1.0
  - six=1.17.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sqlalchemy=2.0.37
  - sqlite=3.45.2
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchmetrics=1.6.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wandb=0.19.4
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - adjusttext==1.3.0
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - cffi==1.17.1
      - colorlog==6.9.0
      - comm==0.2.2
      - cssselect2==0.8.0
      - debugpy==1.8.12
      - defusedxml==0.7.1
      - einops==0.8.1
      - executing==2.2.0
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - llvmlite==0.44.0
      - nest-asyncio==1.6.0
      - numba==0.61.2
      - pluggy==1.6.0
      - pycparser==2.22
      - pynndescent==0.5.13
      - pytest==8.4.1
      - pyzmq==26.2.0
      - sympy==1.13.1
      - tinycss2==1.4.0
      - tornado==6.4.2
      - umap-learn==0.5.7
      - wandb-osh==1.2.2
      - webencodings==0.5.1
