# @package _global_
score_model_args:
  model_name: DiffusionModuleTransformer
  DiffusionModuleTransformer:
    n_blocks: 24
    n_heads: 16
    hidden_size: 1024
    mlp_ratio: 4.0

dataset_args:
  find_unused_parameters: False