# @package _global_
diffusion_process_args:
  train_sigma_distribution_type: af3 # edm | af3 | uniform | logit-normal | proteina
  train_sigma_args:
    edm_P_mean: -1.2
    edm_P_std: 1.3
  sample_sigma_schedule_type: edm # edm | af3 | linear | log
  sample_gamma_schedule_type: edm # edm | proteina | sit | ode
  sigma_min: 0.001
  sigma_max: 80.0
  gamma_min: 1.0
  noise_scale: 1.0
  step_scale: 1.0
  guidance_scale: 0.0 # Guidance scale for classifier-free guidance
  synchronize_sigmas: False
  coordinate_transformation_when_training: "centering_rotation_translation"
  edm_args:
    sigma_data: null
    rho: 7
    use_heun_solver: True
    gamma_0: 0.8